import React from 'react';

export default function Terms() {
    return (
        <main className="min-h-screen text-white py-20 px-4">
            <div className="max-w-3xl mx-auto space-y-8">
                <h1 className="text-4xl font-bold text-orange-500 mb-8">Terms of Service</h1>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
                    <p className="text-gray-400">
                        By accessing and using Roast My Landing Page AI, you accept and agree to be bound by the terms and provision of this agreement.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">2. Description of Service</h2>
                    <p className="text-gray-400">
                        We provide an AI-powered analysis of website landing pages. The &quot;roasts&quot; are generated by artificial intelligence and are intended for entertainment and educational purposes only. We do not guarantee the accuracy or professional validity of the advice given.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">3. User Conduct</h2>
                    <p className="text-gray-400">
                        You agree to use the service only for lawful purposes. You represent that you have the right to submit any URL you provide for analysis.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">4. Disclaimer</h2>
                    <p className="text-gray-400">
                        The service is provided &quot;as is&quot;. We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                    </p>
                </section>
            </div>
        </main>
    );
}
